version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    groups:
      submodules:
        patterns:
          - "*"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/"
    groups:
      python-dependencies:
        patterns:
          - "*"
    schedule:
      interval: "monthly"
