/*----------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
ported to C++ by Csaba Balazs, University of Szeged
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2, or (at your option) any 
later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than 
Coco/R itself) does not fall under the GNU General Public License.
-----------------------------------------------------------------------*/


#if !defined(syrec_COCO_PARSER_H__)
#define syrec_COCO_PARSER_H__

#include <cwchar>
#include <optional>
#include <set>
#include <stdexcept>
#include <string>
#include <variant>
#include <vector>

#include "core/syrec/module.hpp"
#include "core/syrec/parser/method_call_guess.hpp"
#include "core/syrec/parser/operation.hpp"
#include "core/syrec/parser/parser_error_message_generator.hpp"
#include "core/syrec/parser/range_check.hpp"
#include "core/syrec/parser/symbol_table.hpp"
#include "core/syrec/parser/text_utils.hpp"


#include "Scanner.h"

namespace syrec {


class Errors {
public:
	int count;			// number of errors detected

	Errors();
	void SynErr(int line, int col, int n);
	void Error(int line, int col, const wchar_t *s);
	void Warning(int line, int col, const wchar_t *s);
	void Warning(const wchar_t *s);
	void Exception(const wchar_t *s);

}; // Errors

class Parser {
private:
	enum {
		_EOF=0,
		_ident=1,
		_int=2
	};
	int maxT;

	Token *dummyToken;
	int errDist;
	int minErrDist;

	void SynErr(int n);
	void Get();
	void Expect(int n);
	bool StartOf(int s);
	void ExpectWeak(int n, int follow);
	bool WeakSeparator(int n, int syFol, int repFol);

public:
	Scanner *scanner;
	Errors  *errors;

	Token *t;			// last recognized token
	Token *la;			// lookahead token

struct expression_or_constant {
		public:
			expression_or_constant(const unsigned int constant_value) : variants(constant_value)
			{
			}

			expression_or_constant(const expression::ptr &expression) : variants(expression) 
			{
			}
				
			[[nodiscard]] bool is_constant() const {
				return std::holds_alternative<unsigned int>(variants);
			}

			[[nodiscard]] unsigned int get_constant_value() const {
				return std::get<unsigned int>(variants);
			}

			[[nodiscard]] expression::ptr get_expression() const {
				return std::get<expression::ptr>(variants);
			}

			[[nodiscard]] expression::ptr convert_to_expression() const {
				if (is_constant()) {
					const number::ptr &constant_value_wrapper = std::make_shared<number>(get_constant_value());
					// TODO: Fix calculation of bitwidth for constant value
					const expression::ptr expression_for_constant = std::make_shared<numeric_expression>(constant_value_wrapper, 0);
					return expression_for_constant;
				}
				else {
					return get_expression();	
				}
			}
			
		private:
			std::variant<expression::ptr, unsigned int> variants;
	};

	typedef std::optional<std::variant<variable_access::ptr, number::ptr>> signal_evaluation_result;
	typedef std::optional<expression_or_constant> expression_evaluation_result;

	// Place declarations of objects referenced in this ATG
	module::vec modules;
	parser_error_message_generator error_message_generator;
	symbol_table::ptr current_symbol_table_scope;

	// This method will be called by the contructor if it exits.
	// This support is specific to the C++ version of Coco/R.
	void Init() {
		// nothing to do
		symbol_table::open_scope(current_symbol_table_scope);
	}

	// Uncomment this method if cleanup is necessary,
	// this method will be called by the destructor if it exists.
	// This support is specific to the C++ version of Coco/R.
	// void Destroy() {
		// nothing to do
	// }

	[[nodiscard]] bool are_token_values_equal(const wchar_t *my_token_value, const wchar_t *other_token_value) const {
		if (my_token_value == nullptr || other_token_value == nullptr) {
			// TODO: Could also throw exception
			return false;
		}
		return !wcscmp(my_token_value, other_token_value);
	}

	[[nodiscard]] bool token_matches_one_of(const Token *tokenToCheck, std::vector<std::wstring> one_of_many_token_values) const {
        const std::set<std::wstring> set_of_matching_token_values{std::begin(one_of_many_token_values), std::end(one_of_many_token_values)};
        return set_of_matching_token_values.count(tokenToCheck->val);
	}

	[[nodiscard]] bool find_matching_token(std::vector<std::wstring> matching_token_values, std::vector<std::wstring> token_values_allowing_stop_of_search) const {
		const std::set<std::wstring> set_of_matching_token_values { std::begin(matching_token_values), std::end(matching_token_values) };
		const std::set<std::wstring> set_of_token_values_allowing_stop_of_search { std::begin(token_values_allowing_stop_of_search), std::end(token_values_allowing_stop_of_search) };
		bool found_matching_operator = false;
		bool can_cancel_search = false;

		while (!can_cancel_search) {
			const Token *peeked_token = scanner->Peek();
			found_matching_operator = set_of_matching_token_values.count(peeked_token->val);
			can_cancel_search = found_matching_operator || peeked_token->kind == _EOF || set_of_token_values_allowing_stop_of_search.count(peeked_token->val);
		}
		return found_matching_operator;
	}

	[[nodiscard]] bool check_if_is_assign_statement() const {
		const std::vector<std::wstring> matching_tokens = {L"^", L"+", L"-"};
		const std::vector<std::wstring> tokens_resulting_in_check_being_false = {L";", L"<=>"};

		return find_matching_token(matching_tokens, tokens_resulting_in_check_being_false);
	}

	[[nodiscard]] bool check_if_expression_is_binary_expression() const {
		// Since first LL(1) conflict resolver already started peeking and failed to resolve the conflict, we need to reset the peek position to original one
		scanner->ResetPeek();

		const std::set<std::wstring> tokens_resulting_in_check_being_false {L"+", L"-", L"^", L"*", L"/", L"%", L"*>", L"&&", L"||", L"&", L"|", L"<", L">", L"=", L"!=", L"<=", L">="};
		const std::set<std::wstring> set_of_operator_token_values_of_alternative {L"<<", L">>"};

		bool found_matching_operator = false;
		bool can_cancel_search = false;
		int expression_nesting_level = 0;

		while (!can_cancel_search) {
			const Token *peeked_token = scanner->Peek();

			if (are_token_values_equal(peeked_token->val, L"(")) {
				expression_nesting_level++;
			} 
			else if (are_token_values_equal(peeked_token->val, L")")) {
				expression_nesting_level--;
			}
			else {
				found_matching_operator = expression_nesting_level == 0 && tokens_resulting_in_check_being_false.count(peeked_token->val);
				can_cancel_search = found_matching_operator || set_of_operator_token_values_of_alternative.count(peeked_token->val) || peeked_token->kind == _EOF;			
			}

		}
		return found_matching_operator;
	}

	[[nodiscard]] bool is_token_not_nested_number(const Token *token) const {
		if (token == nullptr) {
			return false;
		}
		return token->kind == _int || are_token_values_equal(token->val, L"#") || are_token_values_equal(token->val, L"$");
	}
		
	[[nodiscard]] bool check_if_expression_is_number(const Token *first_token_of_expression) const {
        bool found_matching_operator;
        const std::vector<std::wstring> matching_tokens = {L"^", L"+", L"-", L"*"};

        if (are_token_values_equal(first_token_of_expression->val, L"(")) {
            found_matching_operator = check_if_expression_is_number(scanner->Peek())
                && token_matches_one_of(scanner->Peek(), matching_tokens)
                && check_if_expression_is_number(scanner->Peek())
                && are_token_values_equal(scanner->Peek()->val, L")");
        } else {
            found_matching_operator = is_token_not_nested_number(first_token_of_expression);
        }
        return found_matching_operator;
	}

	[[nodiscard]] bool check_if_expression_is_number() const {
        return la != nullptr && check_if_expression_is_number(la);
	}

	[[nodiscard]] bool check_if_loop_variable_is_defined() const {
		// Since first LL(1) conflict resolver already started peeking and failed to resolve the conflict, we need to reset the peek position to original one
		scanner->ResetPeek();
		const std::vector<std::wstring> matching_tokens = {L"="};
		const std::vector<std::wstring> tokens_resulting_in_check_being_false = {L"rof"};

		return find_matching_token(matching_tokens, tokens_resulting_in_check_being_false);
	}

	[[nodiscard]] bool check_if_loop_iteration_range_start_is_defined() const {
		const std::vector<std::wstring> matching_tokens = {L"to"};
		const std::vector<std::wstring> tokens_resulting_in_check_being_false = {L"rof"};

		return find_matching_token(matching_tokens, tokens_resulting_in_check_being_false);
	}

	[[nodiscard]] std::optional<unsigned int> convert_token_value_to_number(const Token &token) {
		std::optional<unsigned int> token_as_number;
		try {
			token_as_number.emplace(std::stoul(convert_to_uniform_text_format(token.val)));
		} 
		catch (std::invalid_argument const &ex) {
			// TODO: GEN_ERROR
		}
		catch (std::out_of_range const &ex) {
			// TODO: GEN_ERROR
		}
		return token_as_number;
	}

	[[nodiscard]] static std::optional<unsigned int> map_operation_to_assign_operation(const syrec_operation::operation operation) {
		std::optional<unsigned int> mapping_result;
		switch (operation) {
			case syrec_operation::operation::add_assign:
				mapping_result.emplace(assign_statement::add);
				break;
			case syrec_operation::operation::minus_assign:
				mapping_result.emplace(assign_statement::subtract);
				break;
			case syrec_operation::operation::xor_assign:
				mapping_result.emplace(assign_statement::exor);
				break;
			default:
				// TODO: GEN_ERROR ?
				break;
		}
		return mapping_result;
	}

	[[nodiscard]] static std::optional<unsigned int> map_operation_to_unary_operation(const syrec_operation::operation operation) {
		std::optional<unsigned int> mapping_result;
		switch (operation) {
			case syrec_operation::operation::increment_assign:
				mapping_result.emplace(unary_statement::increment);
				break;
			case syrec_operation::operation::decrement_assign:
				mapping_result.emplace(unary_statement::decrement);
				break;
			case syrec_operation::operation::negate_assign:
				mapping_result.emplace(unary_statement::invert);
				break;
			default:
				// TODO: GEN_ERROR ?
				break;
		}
		return mapping_result;
	}

	[[nodiscard]] static std::optional<unsigned int> map_operation_to_shift_operation(const syrec_operation::operation operation) {
		std::optional<unsigned int> mapping_result;
		switch (operation) {
			case syrec_operation::operation::shift_left:
				mapping_result.emplace(shift_expression::left);
				break;
			case syrec_operation::operation::shift_right:
				mapping_result.emplace(shift_expression::right);
				break;
			default:
				// TODO: GEN_ERROR ?
				break;
		}
		return mapping_result;
	}

	[[nodiscard]] static std::optional<unsigned int> map_operation_to_binary_operation(const syrec_operation::operation operation) {
		std::optional<unsigned int> mapping_result;
		switch (operation) {
			case syrec_operation::operation::addition:
				mapping_result.emplace(binary_expression::add);
				break;
			case syrec_operation::operation::subtraction:
				mapping_result.emplace(binary_expression::subtract);
				break;
				case syrec_operation::operation::multiplication:
				mapping_result.emplace(binary_expression::multiply);
				break;		
			case syrec_operation::operation::division:
				mapping_result.emplace(binary_expression::divide);
				break;			
			case syrec_operation::operation::modulo:
				mapping_result.emplace(binary_expression::modulo);
				break;		
			case syrec_operation::operation::upper_bits_multiplication:
				mapping_result.emplace(binary_expression::frac_divide);
				break;		
			case syrec_operation::operation::bitwise_xor:
				mapping_result.emplace(binary_expression::exor);
				break;		
			case syrec_operation::operation::logical_and:
				mapping_result.emplace(binary_expression::logical_and);
				break;		
			case syrec_operation::operation::logical_or:
				mapping_result.emplace(binary_expression::logical_or);
				break;		
			case syrec_operation::operation::bitwise_and:
				mapping_result.emplace(binary_expression::bitwise_and);
				break;	
			case syrec_operation::operation::bitwise_or:
				mapping_result.emplace(binary_expression::bitwise_or);
				break;	
			case syrec_operation::operation::less_than:
				mapping_result.emplace(binary_expression::less_than);
				break;	
			case syrec_operation::operation::greater_than:
				mapping_result.emplace(binary_expression::greater_than);
				break;	
			case syrec_operation::operation::equals:
				mapping_result.emplace(binary_expression::equals);
				break;		
			case syrec_operation::operation::not_equals:
				mapping_result.emplace(binary_expression::not_equals);
				break;		
			case syrec_operation::operation::less_equals:
				mapping_result.emplace(binary_expression::less_equals);
				break;		
			case syrec_operation::operation::greater_equals:
				mapping_result.emplace(binary_expression::greater_equals);
				break;
			default:
				// TODO: GEN_ERROR ?
				break;
		}
		return mapping_result;
	}

	bool check_ident_was_declared(const std::string &ident) const {
		if (!current_symbol_table_scope->contains(ident)) {
			// TOOD: GEN_ERROR
			return false;
		}
		return true;
	}

	[[nodiscard]] static std::optional<unsigned int> get_value_if_expression_is_constant(const expression_evaluation_result &expression){
		std::optional<unsigned int> constant_value;
		if (expression.has_value() && expression.value().is_constant()) {
			constant_value.emplace(expression.value().get_constant_value());
		}
		return constant_value;
	}

	// TODO: Generate error/s in case of exceptions
	[[nodiscard]] static std::optional<unsigned int> apply_unary_operation(const syrec_operation::operation operation, const number::ptr &left_operand) {
		std::optional<unsigned int> operation_result;
		try {
			operation_result.emplace(syrec_operation::apply(operation, left_operand->evaluate({})));
		}
		catch (std::overflow_error &err) {
		
		}
		catch(std::invalid_argument &err) {
		
		}
        return operation_result;
	}

	// TODO: Generate error/s in case of exceptions
	[[nodiscard]] static std::optional<unsigned int> apply_binary_operation(const syrec_operation::operation operation, const number::ptr &left_operand, const number::ptr &right_operand) {
		std::optional<unsigned int> operation_result;
		try {
			operation_result.emplace(syrec_operation::apply(operation, left_operand->evaluate({}), right_operand->evaluate({})));
		}
		catch (std::overflow_error &err) {
		
		}
		catch(std::invalid_argument &err) {
		
		}
        return operation_result;
	}

/*-------------------------------------------------------------------------*/



	Parser(Scanner *scanner);
	~Parser();
	void SemErr(const wchar_t* msg);

	void Number(std::optional<number::ptr> &parsed_number, bool simplify_if_possible );
	void SyReC();
	void Module(std::optional<module::ptr> &parsed_module	);
	void ParameterList(bool &is_valid_module_definition, const module::ptr &module);
	void SignalList(std::optional<std::vector<variable::ptr>> &signals );
	void StatementList(statement::vec &statements );
	void Parameter(std::optional<variable::ptr> &parameter );
	void SignalDeclaration(variable::types variable_type, std::optional<variable::ptr> &declared_signal );
	void Statement(std::optional<statement::ptr> &user_defined_statement );
	void CallStatement(std::optional<statement::ptr> &statement );
	void ForStatement(std::optional<statement::ptr> &statement );
	void IfStatement(std::optional<statement::ptr> &statement );
	void UnaryStatement(std::optional<statement::ptr> &statement );
	void SkipStatement(std::optional<statement::ptr> &statement );
	void AssignStatement(std::optional<statement::ptr> &statement );
	void SwapStatement(std::optional<statement::ptr> &statement );
	void Expression(expression_evaluation_result &user_defined_expression, bool simplify_if_possible);
	void Signal(signal_evaluation_result &signal_access, bool simplify_if_possible);
	void BinaryExpression(expression_evaluation_result &user_defined_binary_expression, bool simplify_if_possible);
	void ShiftExpression(expression_evaluation_result &user_defined_shift_expression, bool simplify_if_possible);
	void UnaryExpression(expression_evaluation_result &unary_expression, bool simplify_if_possible);

	void Parse();

}; // end Parser

} // namespace


#endif

