/*----------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
ported to C++ by Csaba Balazs, University of Szeged
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2, or (at your option) any 
later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than 
Coco/R itself) does not fall under the GNU General Public License.
-----------------------------------------------------------------------*/


#include <wchar.h>
#include "Parser.h"
#include "Scanner.h"


namespace syrec {


void Parser::SynErr(int n) {
	if (errDist >= minErrDist) errors->SynErr(la->line, la->col, n);
	errDist = 0;
}

void Parser::SemErr(const wchar_t* msg) {
	if (errDist >= minErrDist) errors->Error(t->line, t->col, msg);
	errDist = 0;
}

void Parser::Get() {
	for (;;) {
		t = la;
		la = scanner->Scan();
		if (la->kind <= maxT) { ++errDist; break; }

		if (dummyToken != t) {
			dummyToken->kind = t->kind;
			dummyToken->pos = t->pos;
			dummyToken->col = t->col;
			dummyToken->line = t->line;
			dummyToken->next = NULL;
			coco_string_delete(dummyToken->val);
			dummyToken->val = coco_string_create(t->val);
			t = dummyToken;
		}
		la = t;
	}
}

void Parser::Expect(int n) {
	if (la->kind==n) Get(); else { SynErr(n); }
}

void Parser::ExpectWeak(int n, int follow) {
	if (la->kind == n) Get();
	else {
		SynErr(n);
		while (!StartOf(follow)) Get();
	}
}

bool Parser::WeakSeparator(int n, int syFol, int repFol) {
	if (la->kind == n) {Get(); return true;}
	else if (StartOf(repFol)) {return false;}
	else {
		SynErr(n);
		while (!(StartOf(syFol) || StartOf(repFol) || StartOf(0))) {
			Get();
		}
		return StartOf(syFol);
	}
}

void Parser::Number(std::optional<number::ptr> &parsed_number, bool simplify_if_possible ) {
		if (la->kind == _int) {
			Get();
			const std::optional<unsigned int> conversion_result = convert_token_value_to_number(*t);
			if (conversion_result.has_value()) {
			const number::ptr result = std::make_shared<number>(number(conversion_result.value())); 
			parsed_number.emplace(result);
			}
			
		} else if (la->kind == 3 /* "#" */) {
			Get();
			Expect(_ident);
			const std::string signal_ident = convert_to_uniform_text_format(t->val);
			if (check_ident_was_declared(signal_ident)) {
			const auto &symbol_table_entry = current_symbol_table_scope->get_variable(signal_ident);
			if (symbol_table_entry.has_value() && std::holds_alternative<variable::ptr>(symbol_table_entry.value())) {
			parsed_number.emplace(std::make_shared<number>(number(std::get<variable::ptr>(symbol_table_entry.value())->bitwidth)));
			}
			else {
			// TODO: GEN_ERROR, this should not happen but check anyways
			}
			}
			
		} else if (la->kind == 4 /* "$" */) {
			Get();
			Expect(_ident);
			const std::string signal_ident = convert_to_uniform_text_format(t->val);
			if (check_ident_was_declared(signal_ident)) {
			const auto &symbol_table_entry = current_symbol_table_scope->get_variable(signal_ident);
			if (symbol_table_entry.has_value() && std::holds_alternative<number::ptr>(symbol_table_entry.value())) {
			parsed_number.emplace(std::get<number::ptr>(symbol_table_entry.value()));
			}
			else {
			// TODO: GEN_ERROR, this should not happen but check anyways
			}
			}
			
		} else if (la->kind == 5 /* "(" */) {
			std::optional<number::ptr> lhs_operand, rhs_operand;  
			std::optional<syrec_operation::operation> op;
			
			Get();
			Number(lhs_operand, simplify_if_possible);
			if (la->kind == 6 /* "+" */) {
				Get();
				op.emplace(syrec_operation::operation::addition);		
			} else if (la->kind == 7 /* "-" */) {
				Get();
				op.emplace(syrec_operation::operation::subtraction);	
			} else if (la->kind == 8 /* "*" */) {
				Get();
				op.emplace(syrec_operation::operation::multiplication);	
			} else if (la->kind == 9 /* "/" */) {
				Get();
				op.emplace(syrec_operation::operation::division);		
			} else SynErr(56);
			Number(rhs_operand, simplify_if_possible);
			if (op.has_value() && lhs_operand.has_value() && rhs_operand.has_value()){
			const std::optional<unsigned int> lhs_value = evaluate_number_container_to_constant(lhs_operand.value());
			const std::optional<unsigned int> rhs_value = evaluate_number_container_to_constant(rhs_operand.value());
			
			if (lhs_value.has_value() && rhs_value.has_value()) {
			const std::optional<unsigned int> op_result = apply_binary_operation(op.value(),
			lhs_operand.value()->evaluate(loop_variable_mapping_lookup),
			rhs_operand.value()->evaluate(loop_variable_mapping_lookup));
			if (op_result.has_value()) {
			const number::ptr result = std::make_shared<number>(number(op_result.value())); 
			parsed_number.emplace(result);
			}
			}
			}
			
			Expect(10 /* ")" */);
		} else SynErr(57);
}

void Parser::SyReC() {
		std::optional<module::ptr> module;	
		Module(module);
		if (module.has_value()) {
		current_symbol_table_scope->add_entry(module.value());
		this->modules.emplace_back(module.value());
		}
		
		while (la->kind == 11 /* "module" */) {
			module.reset();	
			Module(module);
			if (module.has_value()) {
			const module::ptr well_formed_module = module.value();
			if (current_symbol_table_scope->contains(well_formed_module)) {
			// TODO: GEN_ERROR 
			// TODO: Do not cancel parsing	
			}
			else {
			current_symbol_table_scope->add_entry(well_formed_module);
			this->modules.emplace_back(module.value());
			}
			}
			
		}
}

void Parser::Module(std::optional<module::ptr> &parsed_module	) {
		symbol_table::open_scope(current_symbol_table_scope);
		std::optional<std::vector<variable::ptr>> locals;	
		bool valid_module_definition = false;
		statement::vec module_body {};
		
		Expect(11 /* "module" */);
		Expect(_ident);
		const std::string module_name = convert_to_uniform_text_format(t->val);	
		module::ptr user_defined_module = std::make_shared<module>(module(module_name));
		
		Expect(5 /* "(" */);
		if (la->kind == 13 /* "in" */ || la->kind == 14 /* "out" */ || la->kind == 15 /* "inout" */) {
			ParameterList(valid_module_definition, user_defined_module);
		}
		Expect(10 /* ")" */);
		while (la->kind == 16 /* "wire" */ || la->kind == 17 /* "signal" */) {
			SignalList(locals);
			valid_module_definition &= locals.has_value();	
		}
		StatementList(module_body);
		symbol_table::close_scope(current_symbol_table_scope);
		if (module_body.empty()) {
		valid_module_definition = false;
		// TODO: GEN_ERROR
		}
		
		if (valid_module_definition) {
		user_defined_module->variables = locals.value_or(std::vector<variable::ptr>{});
		for (const auto &statement : module_body) {
		user_defined_module->add_statement(statement);
		}
		parsed_module.emplace(user_defined_module);
		}
		
}

void Parser::ParameterList(bool &is_valid_module_definition, const module::ptr &module) {
		std::optional<variable::ptr> parameter;	
		Parameter(parameter);
		is_valid_module_definition = parameter.has_value();
		if (is_valid_module_definition) {
		module->add_parameter(parameter.value());
		current_symbol_table_scope->add_entry(parameter.value());
		}
		
		while (la->kind == 12 /* "," */) {
			parameter.reset();	
			Get();
			Parameter(parameter);
			is_valid_module_definition = parameter.has_value();
			if (is_valid_module_definition) {	
			const variable::ptr &well_formed_parameter = parameter.value();
			if (!current_symbol_table_scope->contains(well_formed_parameter->name)) {
			module->add_parameter(well_formed_parameter);
			current_symbol_table_scope->add_entry(well_formed_parameter);
			}
			else {
			is_valid_module_definition = false;
			// TODO: GEN_ERROR 
			}
			}
			
		}
}

void Parser::SignalList(std::optional<std::vector<variable::ptr>> &signals ) {
		variable::types signal_type = variable::in;
		std::optional<variable::ptr> declared_signal;
		bool valid_signal_type = true;
		std::vector<variable::ptr> valid_signal_declarations;
		
		if (la->kind == 16 /* "wire" */) {
			Get();
			signal_type = variable::wire;		
		} else if (la->kind == 17 /* "signal" */) {
			Get();
			signal_type = variable::state;		
		} else SynErr(58);
		if (variable::wire != signal_type && variable::state != signal_type) {
		// TODO: GEN_ERROR ?
		// TODO: Do not cancel parsing
		valid_signal_type = false;
		}
		
		SignalDeclaration(signal_type, declared_signal);
		if (valid_signal_type && declared_signal.has_value()) {
		const variable::ptr &valid_signal_declaration = declared_signal.value();
		if (current_symbol_table_scope->contains(valid_signal_declaration->name)) {
		// TODO: GEN_ERROR 
		// TODO: Do not cancel parsing
		}
		else {
		valid_signal_declarations.emplace_back(valid_signal_declaration);
		current_symbol_table_scope->add_entry(valid_signal_declaration);
		}
		}
		
		while (la->kind == 12 /* "," */) {
			declared_signal.reset();			
			Get();
			SignalDeclaration(signal_type, declared_signal);
			if (valid_signal_type && declared_signal.has_value()) {
			const variable::ptr &valid_signal_declaration = declared_signal.value();
			if (current_symbol_table_scope->contains(valid_signal_declaration->name)) {
			// TODO: GEN_ERROR 
			// TODO: Do not cancel parsing
			}
			else {
			valid_signal_declarations.emplace_back(valid_signal_declaration);
			current_symbol_table_scope->add_entry(valid_signal_declaration);
			}
			}
			
		}
		if (valid_signal_declarations.size()){
		signals.emplace(valid_signal_declarations);
		}
		
}

void Parser::StatementList(statement::vec &statements ) {
		std::optional<statement::ptr> user_defined_statement;	
		Statement(user_defined_statement);
		if (user_defined_statement.has_value()) {
		statements.emplace_back(user_defined_statement.value());
		}
		
		while (la->kind == 20 /* ";" */) {
			user_defined_statement.reset();	
			Get();
			Statement(user_defined_statement);
			if (user_defined_statement.has_value()) {
			statements.emplace_back(user_defined_statement.value());
			}
			
		}
}

void Parser::Parameter(std::optional<variable::ptr> &parameter ) {
		variable::types parameter_type = variable::wire;
		bool valid_variable_type = true;
		
		if (la->kind == 13 /* "in" */) {
			Get();
			parameter_type = variable::in;	
		} else if (la->kind == 14 /* "out" */) {
			Get();
			parameter_type = variable::out;	
		} else if (la->kind == 15 /* "inout" */) {
			Get();
			parameter_type = variable::inout;	
		} else SynErr(59);
		if (variable::wire == parameter_type) {
		// TODO: GEN_ERROR 
		// TODO: Do not cancel parsing
		valid_variable_type = false;
		}
		
		SignalDeclaration(parameter_type, parameter);
		if (!valid_variable_type) {
		parameter.reset();
		}
		
}

void Parser::SignalDeclaration(variable::types variable_type, std::optional<variable::ptr> &declared_signal ) {
		std::vector<unsigned int> dimensions{};
		// TODO: Use default bit width
		unsigned int signal_width = 0;	
		bool valid_declaration = true;
		
		Expect(_ident);
		const std::string signal_ident = convert_to_uniform_text_format(t->val);	
		while (la->kind == 18 /* "[" */) {
			Get();
			Expect(_int);
			const std::optional<unsigned int> dimension = convert_token_value_to_number(*t);
			if (!dimension.has_value()) {
			valid_declaration = false;
			// TODO: GEN_ERROR
			}
			else {
			dimensions.emplace_back(dimension.value());	
			}
			
			Expect(19 /* "]" */);
		}
		if (la->kind == 5 /* "(" */) {
			Get();
			Expect(_int);
			const std::optional<unsigned int> user_defined_signal_width = convert_token_value_to_number(*t);
			if (!user_defined_signal_width.has_value()) {
			// TODO: GEN_ERROR
			valid_declaration = false;
			}
			else {
			signal_width = user_defined_signal_width.value();
			}
			
			Expect(10 /* ")" */);
		}
		if (valid_declaration) {
		declared_signal.emplace(std::make_shared<variable>(variable(variable_type, signal_ident, dimensions, signal_width)));
		}
		
}

void Parser::Statement(std::optional<statement::ptr> &user_defined_statement ) {
		if (la->kind == 21 /* "call" */ || la->kind == 22 /* "uncall" */) {
			CallStatement(user_defined_statement);
		} else if (la->kind == 23 /* "for" */) {
			ForStatement(user_defined_statement);
		} else if (la->kind == 29 /* "if" */) {
			IfStatement(user_defined_statement);
		} else if (la->kind == 33 /* "~" */ || la->kind == 34 /* "++" */ || la->kind == 35 /* "--" */) {
			UnaryStatement(user_defined_statement);
		} else if (la->kind == 38 /* "skip" */) {
			SkipStatement(user_defined_statement);
		} else if (check_if_is_assign_statement()) {
			AssignStatement(user_defined_statement);
		} else if (la->kind == _ident) {
			SwapStatement(user_defined_statement);
		} else SynErr(60);
}

void Parser::CallStatement(std::optional<statement::ptr> &statement ) {
		std::optional<bool> is_call_statement;
		std::vector<std::string> callee_arguments {};
		bool valid_call_operation = true;
		std::vector<std::string_view> formal_method_parameters {};
		std::size_t num_actual_parameters = 0;
		
		if (la->kind == 21 /* "call" */) {
			Get();
			is_call_statement.emplace(true);	
		} else if (la->kind == 22 /* "uncall" */) {
			Get();
			is_call_statement.emplace(false);	
		} else SynErr(61);
		valid_call_operation = is_call_statement.has_value();	
		Expect(_ident);
		const std::string method_ident = convert_to_uniform_text_format(t->val);
		method_call_guess::ptr guess_for_method = std::make_shared<method_call_guess>(method_call_guess(current_symbol_table_scope, method_ident));
		if (!guess_for_method->matches_some_options()) {
		// TODO: GEN_ERROR method not found
		valid_call_operation = false;
		}
		
		Expect(5 /* "(" */);
		Expect(_ident);
		std::string variable_ident = convert_to_uniform_text_format(t->val);
		if (check_ident_was_declared(variable_ident)) {
		try {
		guess_for_method->refine(variable_ident);
		valid_call_operation &= guess_for_method->matches_some_options();
		if (valid_call_operation) {
		callee_arguments.emplace_back(variable_ident);
		}
		}
		catch (std::invalid_argument &ex) {
		// TODO: GEN_ERROR
		valid_call_operation = false;
		}
		}
		else {
		// TODO: GEN_ERROR
		}
		num_actual_parameters++;
		
		while (la->kind == 12 /* "," */) {
			Get();
			Expect(_ident);
			variable_ident = convert_to_uniform_text_format(t->val);
			if (check_ident_was_declared(variable_ident)) {
			try {
			guess_for_method->refine(variable_ident);
			valid_call_operation &= guess_for_method->matches_some_options();
			if (valid_call_operation) {
			const variable::ptr actual_parameter_symbol_entry = std::get<variable::ptr>(current_symbol_table_scope->get_variable(variable_ident).value());
			callee_arguments.emplace_back(variable_ident);
			}
			}
			catch (std::invalid_argument &ex) {
			// TODO: GEN_ERROR
			valid_call_operation = false;
			}
			}
			else {
			// TODO: GEN_ERROR
			}
			num_actual_parameters++;
			
		}
		Expect(10 /* ")" */);
		if (!valid_call_operation) {
		return;		
		}
		if (!guess_for_method->matches_some_options()) {
		// TODO: GEN_ERROR
		return;
		}
		
		const std::optional<module::ptr> possible_match_for_guess = guess_for_method->get_remaining_guess();
		if (!possible_match_for_guess.has_value()) {
		// TODO: GEN_ERROR
		return;
		}
		else {
		const module::ptr &matching_module = possible_match_for_guess.value();
		
		if (is_call_statement.value()) {
		statement.emplace(std::make_shared<call_statement>(call_statement(matching_module, callee_arguments)));
		}
		else {
		statement.emplace(std::make_shared<uncall_statement>(uncall_statement(matching_module, callee_arguments)));
		}
		}
		
}

void Parser::ForStatement(std::optional<statement::ptr> &statement ) {
		std::optional<std::string> loop_variable_ident;
		std::optional<number::ptr> iteration_range_start;
		std::optional<number::ptr> iteration_range_end;
		std::optional<number::ptr> custom_step_size;
		bool negative_step_size = false;
		statement::vec loop_body{};
		bool explicit_range_start_defined = false;
		bool explicit_step_size_defined = false;
		
		Expect(23 /* "for" */);
		if (check_if_loop_iteration_range_start_is_defined()) {
			if (check_if_loop_variable_is_defined()) {
				Expect(4 /* "$" */);
				Expect(_ident);
				const std::string &loop_var_ident = convert_to_uniform_text_format(t->val);
				if (!check_ident_was_declared(loop_var_ident)) {
				loop_variable_ident.emplace(convert_to_uniform_text_format(t->val));
				symbol_table::open_scope(current_symbol_table_scope);
				const number::ptr loop_variable_entry = std::make_shared<number>(number(loop_var_ident));
				current_symbol_table_scope->add_entry(loop_variable_entry);
				}
				
				Expect(24 /* "=" */);
			}
			Number(iteration_range_start, false);
			explicit_range_start_defined = true;	
			Expect(25 /* "to" */);
		}
		Number(iteration_range_end, false);
		if (!explicit_range_start_defined){
		iteration_range_start = iteration_range_end;
		}
		
		if (la->kind == 26 /* "step" */) {
			Get();
			explicit_step_size_defined = true;	
			if (la->kind == 7 /* "-" */) {
				Get();
				negative_step_size = true;	
			}
			Number(custom_step_size, false);
			if (custom_step_size.has_value() && !custom_step_size.value()->evaluate({})) {
			// TODO: GEN_ERROR step size cannot be zero ?
			}
			
		}
		if (!explicit_step_size_defined) {
		custom_step_size.emplace(std::make_shared<number>(number(1)));
		}
		
		bool valid_loop_header = loop_variable_ident.has_value() 
						&& (explicit_range_start_defined ? iteration_range_start.has_value() : true)
						&& iteration_range_end.has_value()
						&& (explicit_step_size_defined ? custom_step_size.has_value() : true);
		if (valid_loop_header) {
		const unsigned int iteration_range_start_value = iteration_range_start.value()->evaluate({});
		const unsigned int iteration_range_end_value = iteration_range_end.value()->evaluate({});
		const unsigned int step_size = custom_step_size.value()->evaluate({});
		
		unsigned int num_iterations;
		if ((negative_step_size && iteration_range_end_value > iteration_range_start_value)
		|| (!negative_step_size && iteration_range_start_value > iteration_range_end_value)
		|| !step_size) {
		// TODO: Either generate error or warning
		num_iterations = 0;	
		valid_loop_header = false;
		}
		else {
		num_iterations = negative_step_size 
		? (iteration_range_start_value - iteration_range_end_value)
		: (iteration_range_end_value - iteration_range_start_value);
		num_iterations = (num_iterations + 1) / step_size;
		}
		}
		
		Expect(27 /* "do" */);
		StatementList(loop_body);
		if (loop_body.empty()) {
		// TODO: GEN_ERROR
		}
		
		Expect(28 /* "rof" */);
		if (loop_variable_ident.has_value()) {
		symbol_table::close_scope(current_symbol_table_scope);
		}
		
		// TODO: If a statement must be generated, one could create a skip statement instead of simply returning 
		if (!valid_loop_header || loop_body.empty()) {
		return;
		}
		
		const std::shared_ptr<for_statement> loop_statement = std::make_shared<for_statement>(for_statement());
		loop_statement->loop_variable = loop_variable_ident.value();
		loop_statement->range = std::pair(iteration_range_start.value(), iteration_range_end.value());
		loop_statement->step = custom_step_size.value();
		loop_statement->statements = loop_body;
		statement.emplace(loop_statement);
		
}

void Parser::IfStatement(std::optional<statement::ptr> &statement ) {
		expression_evaluation_result condition;
		expression_evaluation_result closing_condition;
		statement::vec true_branch{};
		statement::vec false_branch{};
		
		Expect(29 /* "if" */);
		Expression(condition, 1u, false);
		Expect(30 /* "then" */);
		StatementList(true_branch);
		Expect(31 /* "else" */);
		StatementList(false_branch);
		Expect(32 /* "fi" */);
		Expression(closing_condition, 1u, false);
		const bool conditional_well_formed = condition.has_value() 
		&& closing_condition.has_value()
		&& !true_branch.empty()
		&& !false_branch.empty();
		if (!conditional_well_formed) {
		return;
		}
		
		const std::shared_ptr<if_statement> &conditional = std::make_shared<if_statement>(if_statement());
		conditional->condition = condition.value().convert_to_expression(1u);
		conditional->fi_condition = closing_condition.value().convert_to_expression(1u);
		conditional->then_statements                    = true_branch;
		conditional->else_statements                    = false_branch;
		statement.emplace(conditional);
		
}

void Parser::UnaryStatement(std::optional<statement::ptr> &statement ) {
		signal_evaluation_result unary_stmt_operand;
		std::optional<syrec_operation::operation> unary_operation;	
		
		if (la->kind == 33 /* "~" */) {
			Get();
			unary_operation.emplace(syrec_operation::operation::negate_assign);	
		} else if (la->kind == 34 /* "++" */) {
			Get();
			unary_operation.emplace(syrec_operation::operation::increment_assign);	
		} else if (la->kind == 35 /* "--" */) {
			Get();
			unary_operation.emplace(syrec_operation::operation::decrement_assign);	
		} else SynErr(62);
		Expect(24 /* "=" */);
		Signal(unary_stmt_operand, false);
		if (!unary_operation.has_value() || !unary_stmt_operand.has_value() || nullptr == std::get<variable_access::ptr>(unary_stmt_operand.value())) {
		return;
		}
		
		const variable_access::ptr unary_operand_variable = std::get<variable_access::ptr>(unary_stmt_operand.value());
		const std::optional<unsigned int> mapped_operation = map_operation_to_unary_operation(unary_operation.value());
		if (mapped_operation.has_value()) {
		statement.emplace(std::make_shared<unary_statement>(unary_statement(mapped_operation.value(), unary_operand_variable)));
		}
		
}

void Parser::SkipStatement(std::optional<statement::ptr> &statement ) {
		Expect(38 /* "skip" */);
		statement.emplace(std::make_shared<skip_statement>(skip_statement()));	
}

void Parser::AssignStatement(std::optional<statement::ptr> &statement ) {
		signal_evaluation_result assign_stmt_lhs;
		expression_evaluation_result assign_stmt_rhs;
		std::optional<syrec_operation::operation> assign_operation;
		unsigned int expression_bitwidth = 1u;
		
		std::optional<variable_access::ptr> assigned_to_obj;
		
		Signal(assign_stmt_lhs, false);
		if (assign_stmt_lhs.has_value() && std::holds_alternative<variable_access::ptr>(assign_stmt_lhs.value())) {
		assigned_to_obj.emplace(std::get<variable_access::ptr>(assign_stmt_lhs.value()));
		expression_bitwidth = assigned_to_obj.value()->bitwidth();
		}
		
		if (la->kind == 36 /* "^" */) {
			Get();
			assign_operation.emplace(syrec_operation::operation::xor_assign);	
		} else if (la->kind == 6 /* "+" */) {
			Get();
			assign_operation.emplace(syrec_operation::operation::add_assign);	
		} else if (la->kind == 7 /* "-" */) {
			Get();
			assign_operation.emplace(syrec_operation::operation::minus_assign);	
		} else SynErr(63);
		Expect(24 /* "=" */);
		Expression(assign_stmt_rhs, expression_bitwidth, false);
		if (!assigned_to_obj.has_value() || !assign_operation.has_value() || !assign_stmt_rhs.has_value()) {
		return;
		}
		// TODO: To not break reversability of operation, check that expression does not contain the assigned to signal 
		const std::optional<unsigned int> mapped_operation = map_operation_to_assign_operation(assign_operation.value());
		if (mapped_operation.has_value()) {
		statement.emplace(std::make_shared<assign_statement>(assign_statement(assigned_to_obj.value(),
		mapped_operation.value(),
		assign_stmt_rhs.value().convert_to_expression(expression_bitwidth))));
		}
		
}

void Parser::SwapStatement(std::optional<statement::ptr> &statement ) {
		signal_evaluation_result swap_me, swap_other;
		bool swap_operator_specified = false;
		
		Signal(swap_me, false);
		Expect(37 /* "<=>" */);
		swap_operator_specified = true;	
		Signal(swap_other, false);
		const bool lhs_operand_valid = swap_me.has_value() && std::holds_alternative<variable_access::ptr>(swap_me.value());
		const bool rhs_operand_valid = swap_other.has_value() && std::holds_alternative<variable_access::ptr>(swap_other.value());
		
		if (swap_operator_specified && lhs_operand_valid && rhs_operand_valid) {
		const variable_access::ptr &lhs = std::get<variable_access::ptr>(swap_me.value());
		const variable_access::ptr &rhs = std::get<variable_access::ptr>(swap_other.value());
		statement.emplace(std::make_shared<swap_statement>(swap_statement(lhs, rhs)));
		}			
		
}

void Parser::Expression(expression_evaluation_result &user_defined_expression, unsigned int bitwidth, bool simplify_if_possible) {
		signal_evaluation_result signal;
		std::optional<number::ptr> number;
		
		if (StartOf(1)) {
			if (check_if_expression_is_number()) {
				Number(number, simplify_if_possible);
				if (number.has_value()) {
				user_defined_expression.emplace(std::make_shared<numeric_expression>(numeric_expression(number.value(), bitwidth)));
				}
				
			} else if (check_if_expression_is_binary_expression()) {
				BinaryExpression(user_defined_expression, bitwidth, simplify_if_possible);
			} else {
				ShiftExpression(user_defined_expression, bitwidth, simplify_if_possible);
			}
		} else if (la->kind == _ident) {
			Signal(signal, simplify_if_possible);
			if (signal.has_value()) {
			if (std::holds_alternative<variable_access::ptr>(signal.value())) {
			const variable_access::ptr &var_access = std::get<variable_access::ptr>(signal.value());
			user_defined_expression.emplace(std::make_shared<variable_expression>(variable_expression(var_access)));
			}
			else if (std::holds_alternative<number::ptr>(signal.value())){
			const number::ptr &number_signal = std::get<number::ptr>(signal.value());
			user_defined_expression.emplace(std::make_shared<numeric_expression>(numeric_expression(number_signal, bitwidth)));
			}
			}
			
		} else if (la->kind == 33 /* "~" */ || la->kind == 52 /* "!" */) {
			UnaryExpression(user_defined_expression, bitwidth, simplify_if_possible);
		} else SynErr(64);
}

void Parser::Signal(signal_evaluation_result &signal_access, bool simplify_if_possible) {
		std::optional<variable::ptr> signal;	
		variable_access::ptr declared_signal_access;
		bool valid_signal_access = true;
		// TODO: Using global zero_based indexing flag to initialize default value
		std::size_t dimension_index = 0;
		unsigned int index_expression_bitwidth = 1u;
		
		Expect(_ident);
		const std::string signal_ident = convert_to_uniform_text_format(t->val);
		if (check_ident_was_declared(signal_ident)) {
		const auto symbol_table_entry = current_symbol_table_scope->get_variable(signal_ident).value();
		if (std::holds_alternative<variable::ptr>(symbol_table_entry)) {
		signal.emplace(std::get<variable::ptr>(symbol_table_entry));
		declared_signal_access = std::make_shared<variable_access>(variable_access());
		declared_signal_access->set_var(signal.value());
		index_expression_bitwidth = signal.value()->bitwidth;
		}
		else {
		valid_signal_access = false;
		}
		}
		else {
		valid_signal_access = false;
		}
		
		while (la->kind == 18 /* "[" */) {
			Get();
			expression_evaluation_result index_expression;	
			Expression(index_expression, index_expression_bitwidth, simplify_if_possible);
			valid_signal_access &= index_expression.has_value();
			if (signal.has_value() && index_expression.has_value()) {
			const std::optional<unsigned int> &optional_dimension_access_value = get_value_if_expression_is_constant(index_expression);
			
			if (optional_dimension_access_value.has_value()) {
			const unsigned int constant_dimension_access_value = optional_dimension_access_value.value();
			
			// TODO: Using global zero_based indexing flag
			if (!range_check::is_valid_dimension_access(signal.value(), dimension_index, constant_dimension_access_value, true)) {
			valid_signal_access = false;
			
			// TODO: Using global zero_based indexing flag
			const range_check::valid_index_access_range valid_dimension_access_range = range_check::get_valid_dimension_access_range(signal.value(), dimension_index, true).value();
			// TODO: GEN_ERROR
			}
			else {
			declared_signal_access->indexes.emplace_back(index_expression.value().convert_to_expression(index_expression_bitwidth));
			}
			}
			else {
			declared_signal_access->indexes.emplace_back(index_expression.value().get_expression());
			}
			}
			dimension_index++;
			
			Expect(19 /* "]" */);
		}
		if (la->kind == 39 /* "." */) {
			std::optional<number::ptr> range_start, range_end;
			bool defined_range = false;
			
			Get();
			Number(range_start, false);
			if (la->kind == 40 /* ":" */) {
				Get();
				Number(range_end, false);
				defined_range = true;	
			}
			valid_signal_access &= range_start.has_value() && (defined_range ? range_end.has_value() : true);
			if (valid_signal_access) {
			const variable::ptr &accessed_variable = signal.value();
			
			const bool is_bit_access = !range_end.has_value();
			const std::pair<number::ptr, number::ptr> range(range_start.value(), is_bit_access ? range_start.value() : range_end.value());
			const std::pair<std::size_t, std::size_t> range_values(range.first->evaluate({}), range.second->evaluate({}));
			
			if (is_bit_access) {
			// TODO: Check bitwidth is within range [0, bitwidth - 1]
			// TODO: Using global zero_based indexing flag
			if (!range_check::is_valid_bit_access(accessed_variable, range_values.first, true)) {
			valid_signal_access = false;
			// TODO: GEN_ERROR
			// TODO: Using global zero_based indexing flag
			const range_check::valid_index_access_range valid_dimension_access_range = range_check::get_valid_bit_access_range(accessed_variable, true);
			}
			}
			else {
			// TODO: Check user defined range is within [0, bitwidth - 1]
			// TODO: Using global zero_based indexing flag
			if (!range_check::is_valid_range_access(accessed_variable, range_values, true)){
			valid_signal_access = false;
			// TODO: GEN_ERROR
			// TODO: Using global zero_based indexing flag
			const range_check::valid_index_access_range valid_dimension_access_range = range_check::get_valid_range_access_range(accessed_variable, true);
			}
			}
			
			if (valid_signal_access){
			declared_signal_access->range.emplace(range);
			}
			}
			
		}
		if (valid_signal_access) {
		signal_access.emplace(declared_signal_access);
		}
		
}

void Parser::BinaryExpression(expression_evaluation_result &user_defined_binary_expression, unsigned int bitwidth, bool simplify_if_possible) {
		expression_evaluation_result binary_expr_lhs;
		expression_evaluation_result binary_expr_rhs;
		std::optional<syrec_operation::operation> binary_operation;
		unsigned int operands_bitwidth = 0u;
		
		Expect(5 /* "(" */);
		Expression(binary_expr_lhs, bitwidth, simplify_if_possible);
		if (binary_expr_lhs.has_value()) {
		operands_bitwidth = std::max(binary_expr_lhs->convert_to_expression(bitwidth)->bitwidth(), bitwidth);
		}
		
		switch (la->kind) {
		case 6 /* "+" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::addition);	
			break;
		}
		case 7 /* "-" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::subtraction);	
			break;
		}
		case 36 /* "^" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::bitwise_xor);	
			break;
		}
		case 8 /* "*" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::multiplication);	
			break;
		}
		case 9 /* "/" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::division);	
			break;
		}
		case 41 /* "%" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::modulo);	
			break;
		}
		case 42 /* "*>" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::upper_bits_multiplication);	
			break;
		}
		case 43 /* "&&" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::logical_and);	
			break;
		}
		case 44 /* "||" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::logical_or);	
			break;
		}
		case 45 /* "&" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::bitwise_and);	
			break;
		}
		case 46 /* "|" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::bitwise_or);	
			break;
		}
		case 47 /* "<" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::less_than);	
			break;
		}
		case 48 /* ">" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::greater_than);	
			break;
		}
		case 24 /* "=" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::equals);	
			break;
		}
		case 49 /* "!=" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::not_equals);	
			break;
		}
		case 50 /* "<=" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::less_equals);	
			break;
		}
		case 51 /* ">=" */: {
			Get();
			binary_operation.emplace(syrec_operation::operation::greater_equals);	
			break;
		}
		default: SynErr(65); break;
		}
		Expression(binary_expr_rhs, operands_bitwidth, simplify_if_possible);
		Expect(10 /* ")" */);
		if (binary_expr_lhs.has_value() && binary_operation.has_value() && binary_expr_rhs.has_value()) {
		const std::optional<unsigned int> mapped_operation = map_operation_to_binary_operation(binary_operation.value());
		if (mapped_operation.has_value()) {
			if (binary_expr_lhs->is_constant() && binary_expr_rhs->is_constant()) {
				const unsigned int binary_expr_lhs_value = binary_expr_lhs->get_constant_value();
				const unsigned int binary_expr_rhs_value = binary_expr_rhs->get_constant_value();
				const std::optional<unsigned int> evaluation_result = apply_binary_operation(binary_operation.value(),
																binary_expr_lhs_value, binary_expr_rhs_value);
				if (evaluation_result.has_value()) {
					user_defined_binary_expression.emplace(evaluation_result.value());
				}
			}
			else {
				const expression::ptr lhs_operand = binary_expr_lhs->convert_to_expression(operands_bitwidth);
				const expression::ptr rhs_operand = binary_expr_rhs->convert_to_expression(operands_bitwidth);
				user_defined_binary_expression.emplace(std::make_shared<binary_expression>(binary_expression(lhs_operand,
									mapped_operation.value(),
									rhs_operand)));
			}
		}
		}
		
}

void Parser::ShiftExpression(expression_evaluation_result &user_defined_shift_expression, unsigned int bitwidth, bool simplify_if_possible) {
		expression_evaluation_result shift_expression_lhs;
		std::optional<number::ptr> shift_amount;
		std::optional<syrec_operation::operation> shift_operation;
		
		Expect(5 /* "(" */);
		Expression(shift_expression_lhs, bitwidth, simplify_if_possible);
		if (la->kind == 53 /* "<<" */) {
			Get();
			shift_operation.emplace(syrec_operation::operation::shift_left);	
		} else if (la->kind == 54 /* ">>" */) {
			Get();
			shift_operation.emplace(syrec_operation::operation::shift_right);	
		} else SynErr(66);
		Number(shift_amount, simplify_if_possible);
		if (shift_expression_lhs.has_value() && shift_operation.has_value() && shift_amount.has_value()) {
		const std::optional<unsigned int> mapped_shift_operation = map_operation_to_shift_operation(shift_operation.value());
		const expression::ptr lhs_operand_expression = shift_expression_lhs.value().convert_to_expression(bitwidth);
		
		// One could replace the shift statement with a skip statement if the shift amount is zero 
		const std::optional<unsigned int> shift_amount_value_evaluated = evaluate_number_container_to_constant(shift_amount.value());
		if (shift_amount_value_evaluated.has_value() && shift_expression_lhs.value().is_constant()) {
		const unsigned int shift_operand_lhs_value = shift_expression_lhs.value().get_constant_value();
            const std::optional<unsigned int> shift_application_result = syrec_operation::apply(shift_operation.value(), shift_operand_lhs_value,
                                                                                                shift_amount_value_evaluated.value());
		
		if (shift_application_result.has_value()) {
		user_defined_shift_expression.emplace(expression_or_constant(shift_application_result.value()));
		}
		else {
		// TODO: GEN_ERROR
		return;
		}
		}
		else {
		const expression::ptr lhs_operand_expression = shift_expression_lhs.value().convert_to_expression(bitwidth);
		user_defined_shift_expression.emplace(std::make_shared<shift_expression>(lhs_operand_expression,
		mapped_shift_operation.value(),
		shift_amount.value()));
		}
		}
		
		Expect(10 /* ")" */);
}

void Parser::UnaryExpression(expression_evaluation_result &unary_expression, unsigned int bitwidth, bool simplify_if_possible) {
		expression_evaluation_result unary_expression_operand;
		std::optional<syrec_operation::operation> unary_operation;
		
		if (la->kind == 52 /* "!" */) {
			Get();
			unary_operation.emplace(syrec_operation::operation::logical_negation);	
		} else if (la->kind == 33 /* "~" */) {
			Get();
			unary_operation.emplace(syrec_operation::operation::bitwise_negation);	
		} else SynErr(67);
		Expression(unary_expression_operand, bitwidth, simplify_if_possible);
		if (unary_operation.has_value() && unary_expression_operand.has_value()){
		// TODO:
		}
		
		// TODO: Notify user (i.e. via error) that reference parser currently does not support unary statements - we will ignore them for now
		
}




// If the user declared a method Init and a mehtod Destroy they should
// be called in the contructur and the destructor respctively.
//
// The following templates are used to recognize if the user declared
// the methods Init and Destroy.

template<typename T>
struct ParserInitExistsRecognizer {
	template<typename U, void (U::*)() = &U::Init>
	struct ExistsIfInitIsDefinedMarker{};

	struct InitIsMissingType {
		char dummy1;
	};
	
	struct InitExistsType {
		char dummy1; char dummy2;
	};

	// exists always
	template<typename U>
	static InitIsMissingType is_here(...);

	// exist only if ExistsIfInitIsDefinedMarker is defined
	template<typename U>
	static InitExistsType is_here(ExistsIfInitIsDefinedMarker<U>*);

	enum { InitExists = (sizeof(is_here<T>(NULL)) == sizeof(InitExistsType)) };
};

template<typename T>
struct ParserDestroyExistsRecognizer {
	template<typename U, void (U::*)() = &U::Destroy>
	struct ExistsIfDestroyIsDefinedMarker{};

	struct DestroyIsMissingType {
		char dummy1;
	};
	
	struct DestroyExistsType {
		char dummy1; char dummy2;
	};

	// exists always
	template<typename U>
	static DestroyIsMissingType is_here(...);

	// exist only if ExistsIfDestroyIsDefinedMarker is defined
	template<typename U>
	static DestroyExistsType is_here(ExistsIfDestroyIsDefinedMarker<U>*);

	enum { DestroyExists = (sizeof(is_here<T>(NULL)) == sizeof(DestroyExistsType)) };
};

// The folloing templates are used to call the Init and Destroy methods if they exist.

// Generic case of the ParserInitCaller, gets used if the Init method is missing
template<typename T, bool = ParserInitExistsRecognizer<T>::InitExists>
struct ParserInitCaller {
	static void CallInit(T *t) {
		// nothing to do
	}
};

// True case of the ParserInitCaller, gets used if the Init method exists
template<typename T>
struct ParserInitCaller<T, true> {
	static void CallInit(T *t) {
		t->Init();
	}
};

// Generic case of the ParserDestroyCaller, gets used if the Destroy method is missing
template<typename T, bool = ParserDestroyExistsRecognizer<T>::DestroyExists>
struct ParserDestroyCaller {
	static void CallDestroy(T *t) {
		// nothing to do
	}
};

// True case of the ParserDestroyCaller, gets used if the Destroy method exists
template<typename T>
struct ParserDestroyCaller<T, true> {
	static void CallDestroy(T *t) {
		t->Destroy();
	}
};

void Parser::Parse() {
	t = NULL;
	la = dummyToken = new Token();
	la->val = coco_string_create(L"Dummy Token");
	Get();
	SyReC();
	Expect(0);
}

Parser::Parser(Scanner *scanner) {
	maxT = 55;

	ParserInitCaller<Parser>::CallInit(this);
	dummyToken = NULL;
	t = la = NULL;
	minErrDist = 2;
	errDist = minErrDist;
	this->scanner = scanner;
	errors = new Errors();
}

bool Parser::StartOf(int s) {
	const bool T = true;
	const bool x = false;

	static bool set[2][57] = {
		{T,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x},
		{x,x,T,T, T,T,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x}
	};



	return set[s][la->kind];
}

Parser::~Parser() {
	ParserDestroyCaller<Parser>::CallDestroy(this);
	delete errors;
	delete dummyToken;
}

Errors::Errors() {
	count = 0;
}

void Errors::SynErr(int line, int col, int n) {
	wchar_t* s;
	switch (n) {
			case 0: s = coco_string_create(L"EOF expected"); break;
			case 1: s = coco_string_create(L"ident expected"); break;
			case 2: s = coco_string_create(L"int expected"); break;
			case 3: s = coco_string_create(L"\"#\" expected"); break;
			case 4: s = coco_string_create(L"\"$\" expected"); break;
			case 5: s = coco_string_create(L"\"(\" expected"); break;
			case 6: s = coco_string_create(L"\"+\" expected"); break;
			case 7: s = coco_string_create(L"\"-\" expected"); break;
			case 8: s = coco_string_create(L"\"*\" expected"); break;
			case 9: s = coco_string_create(L"\"/\" expected"); break;
			case 10: s = coco_string_create(L"\")\" expected"); break;
			case 11: s = coco_string_create(L"\"module\" expected"); break;
			case 12: s = coco_string_create(L"\",\" expected"); break;
			case 13: s = coco_string_create(L"\"in\" expected"); break;
			case 14: s = coco_string_create(L"\"out\" expected"); break;
			case 15: s = coco_string_create(L"\"inout\" expected"); break;
			case 16: s = coco_string_create(L"\"wire\" expected"); break;
			case 17: s = coco_string_create(L"\"signal\" expected"); break;
			case 18: s = coco_string_create(L"\"[\" expected"); break;
			case 19: s = coco_string_create(L"\"]\" expected"); break;
			case 20: s = coco_string_create(L"\";\" expected"); break;
			case 21: s = coco_string_create(L"\"call\" expected"); break;
			case 22: s = coco_string_create(L"\"uncall\" expected"); break;
			case 23: s = coco_string_create(L"\"for\" expected"); break;
			case 24: s = coco_string_create(L"\"=\" expected"); break;
			case 25: s = coco_string_create(L"\"to\" expected"); break;
			case 26: s = coco_string_create(L"\"step\" expected"); break;
			case 27: s = coco_string_create(L"\"do\" expected"); break;
			case 28: s = coco_string_create(L"\"rof\" expected"); break;
			case 29: s = coco_string_create(L"\"if\" expected"); break;
			case 30: s = coco_string_create(L"\"then\" expected"); break;
			case 31: s = coco_string_create(L"\"else\" expected"); break;
			case 32: s = coco_string_create(L"\"fi\" expected"); break;
			case 33: s = coco_string_create(L"\"~\" expected"); break;
			case 34: s = coco_string_create(L"\"++\" expected"); break;
			case 35: s = coco_string_create(L"\"--\" expected"); break;
			case 36: s = coco_string_create(L"\"^\" expected"); break;
			case 37: s = coco_string_create(L"\"<=>\" expected"); break;
			case 38: s = coco_string_create(L"\"skip\" expected"); break;
			case 39: s = coco_string_create(L"\".\" expected"); break;
			case 40: s = coco_string_create(L"\":\" expected"); break;
			case 41: s = coco_string_create(L"\"%\" expected"); break;
			case 42: s = coco_string_create(L"\"*>\" expected"); break;
			case 43: s = coco_string_create(L"\"&&\" expected"); break;
			case 44: s = coco_string_create(L"\"||\" expected"); break;
			case 45: s = coco_string_create(L"\"&\" expected"); break;
			case 46: s = coco_string_create(L"\"|\" expected"); break;
			case 47: s = coco_string_create(L"\"<\" expected"); break;
			case 48: s = coco_string_create(L"\">\" expected"); break;
			case 49: s = coco_string_create(L"\"!=\" expected"); break;
			case 50: s = coco_string_create(L"\"<=\" expected"); break;
			case 51: s = coco_string_create(L"\">=\" expected"); break;
			case 52: s = coco_string_create(L"\"!\" expected"); break;
			case 53: s = coco_string_create(L"\"<<\" expected"); break;
			case 54: s = coco_string_create(L"\">>\" expected"); break;
			case 55: s = coco_string_create(L"??? expected"); break;
			case 56: s = coco_string_create(L"invalid Number"); break;
			case 57: s = coco_string_create(L"invalid Number"); break;
			case 58: s = coco_string_create(L"invalid SignalList"); break;
			case 59: s = coco_string_create(L"invalid Parameter"); break;
			case 60: s = coco_string_create(L"invalid Statement"); break;
			case 61: s = coco_string_create(L"invalid CallStatement"); break;
			case 62: s = coco_string_create(L"invalid UnaryStatement"); break;
			case 63: s = coco_string_create(L"invalid AssignStatement"); break;
			case 64: s = coco_string_create(L"invalid Expression"); break;
			case 65: s = coco_string_create(L"invalid BinaryExpression"); break;
			case 66: s = coco_string_create(L"invalid ShiftExpression"); break;
			case 67: s = coco_string_create(L"invalid UnaryExpression"); break;

		default:
		{
			wchar_t format[20];
			coco_swprintf(format, 20, L"error %d", n);
			s = coco_string_create(format);
		}
		break;
	}
	wprintf(L"-- line %d col %d: %ls\n", line, col, s);
	coco_string_delete(s);
	count++;
}

void Errors::Error(int line, int col, const wchar_t *s) {
	wprintf(L"-- line %d col %d: %ls\n", line, col, s);
	count++;
}

void Errors::Warning(int line, int col, const wchar_t *s) {
	wprintf(L"-- line %d col %d: %ls\n", line, col, s);
}

void Errors::Warning(const wchar_t *s) {
	wprintf(L"%ls\n", s);
}

void Errors::Exception(const wchar_t* s) {
	wprintf(L"%ls", s); 
	exit(1);
}

} // namespace

