/*----------------------------------------------------------------------
Compiler Generator Coco/R,
Copyright (c) 1990, 2004 Hanspeter Moessenboeck, University of Linz
extended by M. Loeberbauer & A. Woess, Univ. of Linz
ported to C++ by Csaba Balazs, University of Szeged
with improvements by Pat Terry, Rhodes University

This program is free software; you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by the 
Free Software Foundation; either version 2, or (at your option) any 
later version.

This program is distributed in the hope that it will be useful, but 
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
for more details.

You should have received a copy of the GNU General Public License along 
with this program; if not, write to the Free Software Foundation, Inc., 
59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

As an exception, it is allowed to write an extension of Coco/R that is
used as a plugin in non-free software.

If not otherwise stated, any source code generated by Coco/R (other than 
Coco/R itself) does not fall under the GNU General Public License.
-----------------------------------------------------------------------*/


#include <wchar.h>
#include "Parser.h"
#include "Scanner.h"


namespace syrec {


void Parser::SynErr(int n) {
	if (errDist >= minErrDist) errors->SynErr(la->line, la->col, n);
	errDist = 0;
}

void Parser::SemErr(const wchar_t* msg) {
	if (errDist >= minErrDist) errors->Error(t->line, t->col, msg);
	errDist = 0;
}

void Parser::Get() {
	for (;;) {
		t = la;
		la = scanner->Scan();
		if (la->kind <= maxT) { ++errDist; break; }

		if (dummyToken != t) {
			dummyToken->kind = t->kind;
			dummyToken->pos = t->pos;
			dummyToken->col = t->col;
			dummyToken->line = t->line;
			dummyToken->next = NULL;
			coco_string_delete(dummyToken->val);
			dummyToken->val = coco_string_create(t->val);
			t = dummyToken;
		}
		la = t;
	}
}

void Parser::Expect(int n) {
	if (la->kind==n) Get(); else { SynErr(n); }
}

void Parser::ExpectWeak(int n, int follow) {
	if (la->kind == n) Get();
	else {
		SynErr(n);
		while (!StartOf(follow)) Get();
	}
}

bool Parser::WeakSeparator(int n, int syFol, int repFol) {
	if (la->kind == n) {Get(); return true;}
	else if (StartOf(repFol)) {return false;}
	else {
		SynErr(n);
		while (!(StartOf(syFol) || StartOf(repFol) || StartOf(0))) {
			Get();
		}
		return StartOf(syFol);
	}
}

void Parser::Number(std::optional<number::ptr> &parsed_number ) {
		if (la->kind == _int) {
			Get();
			const std::optional<unsigned int> conversion_result = convert_token_value_to_number(*t);
			if (conversion_result.has_value()) {
			const number::ptr result = std::make_shared<number>(number(conversion_result.value())); 
			parsed_number.emplace(result);
			}
			else {
			// TODO: GEN_ERROR
			}
			
		} else if (la->kind == 3 /* "#" */) {
			Get();
			Expect(_ident);
		} else if (la->kind == 4 /* "$" */) {
			Get();
			Expect(_ident);
		} else if (la->kind == 5 /* "(" */) {
			std::optional<number::ptr> lhs_operand, rhs_operand;  
			std::optional<syrec_operation::operation> op;
			
			Get();
			Number(lhs_operand);
			if (la->kind == 6 /* "+" */) {
				Get();
				op.emplace(syrec_operation::operation::addition);		
			} else if (la->kind == 7 /* "-" */) {
				Get();
				op.emplace(syrec_operation::operation::subtraction);	
			} else if (la->kind == 8 /* "*" */) {
				Get();
				op.emplace(syrec_operation::operation::multiplication);	
			} else if (la->kind == 9 /* "/" */) {
				Get();
				op.emplace(syrec_operation::operation::division);		
			} else SynErr(56);
			Number(rhs_operand);
			if (op.has_value() && lhs_operand.has_value() && rhs_operand.has_value()){
			const std::optional<unsigned int> op_result = syrec_operation::apply(op.value(), lhs_operand.value(), rhs_operand.value());
			if (op_result.has_value()) {
			const number::ptr result = std::make_shared<number>(number(op_result.value())); 
			parsed_number.emplace(result);
			}
			else {
			// TODO: GEN_ERROR
			}
			}
			
			Expect(10 /* ")" */);
		} else SynErr(57);
}

void Parser::SyReC() {
		std::optional<module::ptr> module;	
		Module(module);
		if (module.has_value()) {
		current_symbol_table_scope->add_entry(module.value());
		}
		
		while (la->kind == 11 /* "module" */) {
			module.reset();	
			Module(module);
			if (module.has_value()) {
			const module::ptr well_formed_module = module.value();
			if (current_symbol_table_scope->contains(well_formed_module)) {
			// TODO: GEN_ERROR 
			// TODO: Do not cancel parsing	
			}
			else {
			current_symbol_table_scope->add_entry(well_formed_module);
			}
			}
			
		}
}

void Parser::Module(std::optional<module::ptr> &parsed_module	) {
		symbol_table::open_scope(current_symbol_table_scope);
		std::optional<std::vector<variable::ptr>> locals;	
		bool valid_module_definition = false;
		statement::vec module_body {};
		
		Expect(11 /* "module" */);
		Expect(_ident);
		const std::string module_name = convert_to_uniform_text_format(t->val);	
		module::ptr user_defined_module = std::make_shared<module>(module(module_name));
		
		Expect(5 /* "(" */);
		if (la->kind == 13 /* "in" */ || la->kind == 14 /* "out" */ || la->kind == 15 /* "inout" */) {
			ParameterList(valid_module_definition, user_defined_module);
		}
		Expect(10 /* ")" */);
		while (la->kind == 16 /* "wire" */ || la->kind == 17 /* "signal" */) {
			SignalList(locals);
			valid_module_definition &= locals.has_value();	
		}
		StatementList(module_body);
		symbol_table::close_scope(current_symbol_table_scope);
		if (module_body.empty()) {
		valid_module_definition = false;
		// TODO: GEN_ERROR
		}
		
		if (valid_module_definition) {
		user_defined_module->variables = locals.value_or(std::vector<variable::ptr>{});
		for (const auto &statement : module_body) {
		user_defined_module->add_statement(statement);
		}
		parsed_module.emplace(user_defined_module);
		}
		
}

void Parser::ParameterList(bool &is_valid_module_definition, const module::ptr &module) {
		std::optional<variable::ptr> parameter;	
		Parameter(parameter);
		is_valid_module_definition = parameter.has_value();
		if (is_valid_module_definition) {
		module->add_parameter(parameter.value());
		current_symbol_table_scope->add_entry(parameter.value());
		}
		
		while (la->kind == 12 /* "," */) {
			parameter.reset();	
			Get();
			Parameter(parameter);
			is_valid_module_definition = parameter.has_value();
			const variable::ptr well_formed_parameter = parameter.value();
			if (is_valid_module_definition && !current_symbol_table_scope->contains(well_formed_parameter->name)) {
			module->add_parameter(well_formed_parameter);
			current_symbol_table_scope->add_entry(well_formed_parameter);
			}
			else {
			// TODO: GEN_ERROR 
			}
			
		}
}

void Parser::SignalList(std::optional<std::vector<variable::ptr>> &signals ) {
		variable::types signal_type = variable::in;
		std::optional<variable::ptr> declared_signal;
		bool valid_signal_type = true;
		std::vector<variable::ptr> valid_signal_declarations;
		
		if (la->kind == 16 /* "wire" */) {
			Get();
			signal_type = variable::wire;		
		} else if (la->kind == 17 /* "signal" */) {
			Get();
			signal_type = variable::state;		
		} else SynErr(58);
		if (variable::wire != signal_type && variable::state != signal_type) {
		// TODO: GEN_ERROR ?
		// TODO: Do not cancel parsing
		valid_signal_type = false;
		}
		
		SignalDeclaration(signal_type, declared_signal);
		if (valid_signal_type && declared_signal.has_value()) {
		const variable::ptr &valid_signal_declaration = declared_signal.value();
		if (current_symbol_table_scope->contains(valid_signal_declaration->name)) {
		// TODO: GEN_ERROR 
		// TODO: Do not cancel parsing
		}
		else {
		valid_signal_declarations.emplace_back(valid_signal_declaration);
		current_symbol_table_scope->add_entry(valid_signal_declaration);
		}
		}
		
		while (la->kind == 12 /* "," */) {
			declared_signal.reset();			
			Get();
			SignalDeclaration(signal_type, declared_signal);
			if (valid_signal_type && declared_signal.has_value()) {
			const variable::ptr &valid_signal_declaration = declared_signal.value();
			if (current_symbol_table_scope->contains(valid_signal_declaration->name)) {
			// TODO: GEN_ERROR 
			// TODO: Do not cancel parsing
			}
			else {
			valid_signal_declarations.emplace_back(valid_signal_declaration);
			current_symbol_table_scope->add_entry(valid_signal_declaration);
			}
			}
			
		}
		if (valid_signal_declarations.size()){
		signals.emplace(valid_signal_declarations);
		}
		
}

void Parser::StatementList(statement::vec &statements ) {
		std::optional<statement::ptr> user_defined_statement;	
		Statement(user_defined_statement);
		if (user_defined_statement.has_value()) {
		statements.emplace_back(user_defined_statement.value());
		}
		
		while (la->kind == 20 /* ";" */) {
			user_defined_statement.reset();	
			Get();
			Statement(user_defined_statement);
			if (user_defined_statement.has_value()) {
			statements.emplace_back(user_defined_statement.value());
			}
			
		}
}

void Parser::Parameter(std::optional<variable::ptr> &parameter ) {
		variable::types parameter_type = variable::wire;
		bool valid_variable_type = true;
		
		if (la->kind == 13 /* "in" */) {
			Get();
			parameter_type = variable::in;	
		} else if (la->kind == 14 /* "out" */) {
			Get();
			parameter_type = variable::out;	
		} else if (la->kind == 15 /* "inout" */) {
			Get();
			parameter_type = variable::inout;	
		} else SynErr(59);
		if (variable::wire == parameter_type) {
		// TODO: GEN_ERROR 
		// TODO: Do not cancel parsing
		valid_variable_type = false;
		}
		
		SignalDeclaration(parameter_type, parameter);
		if (!valid_variable_type) {
		parameter.reset();
		}
		
}

void Parser::SignalDeclaration(variable::types variable_type, std::optional<variable::ptr> &declared_signal ) {
		std::vector<unsigned int> dimensions{};
		// TODO: Use default bit width
		unsigned int signal_width = 0;	
		bool valid_declaration = true;
		
		Expect(_ident);
		const std::string signal_ident = convert_to_uniform_text_format(t->val);	
		while (la->kind == 18 /* "[" */) {
			Get();
			Expect(_int);
			const std::optional<unsigned int> dimension = convert_token_value_to_number(*t);
			if (!dimension.has_value()) {
			valid_declaration = false;
			// TODO: GEN_ERROR
			}
			else {
			dimensions.emplace_back(dimension.value());	
			}
			
			Expect(19 /* "]" */);
		}
		if (la->kind == 5 /* "(" */) {
			Get();
			Expect(_int);
			const std::optional<unsigned int> user_defined_signal_width = convert_token_value_to_number(*t);
			if (!user_defined_signal_width.has_value()) {
			// TODO: GEN_ERROR
			valid_declaration = false;
			}
			else {
			signal_width = user_defined_signal_width.value();
			}
			
			Expect(10 /* ")" */);
		}
		if (valid_declaration) {
		declared_signal.emplace(std::make_shared<variable>(variable(variable_type, signal_ident, dimensions, signal_width)));
		}
		
}

void Parser::Statement(std::optional<statement::ptr> &user_defined_statement ) {
		if (la->kind == 21 /* "call" */ || la->kind == 22 /* "uncall" */) {
			CallStatement(user_defined_statement);
		} else if (la->kind == 23 /* "for" */) {
			ForStatement(user_defined_statement);
		} else if (la->kind == 29 /* "if" */) {
			IfStatement(user_defined_statement);
		} else if (la->kind == 33 /* "~" */ || la->kind == 34 /* "++" */ || la->kind == 35 /* "--" */) {
			UnaryStatement(user_defined_statement);
		} else if (la->kind == 38 /* "skip" */) {
			SkipStatement(user_defined_statement);
		} else if (check_if_is_assign_statement()) {
			AssignStatement(user_defined_statement);
		} else if (la->kind == _ident) {
			SwapStatement(user_defined_statement);
		} else SynErr(60);
}

void Parser::CallStatement(std::optional<statement::ptr> &statement ) {
		if (la->kind == 21 /* "call" */) {
			Get();
		} else if (la->kind == 22 /* "uncall" */) {
			Get();
		} else SynErr(61);
		Expect(_ident);
		Expect(5 /* "(" */);
		Expect(_ident);
		while (la->kind == 12 /* "," */) {
			Get();
			Expect(_ident);
		}
		Expect(10 /* ")" */);
}

void Parser::ForStatement(std::optional<statement::ptr> &statement ) {
		std::optional<number::ptr> number;
		statement::vec loop_body{};
		
		Expect(23 /* "for" */);
		if (check_if_loop_iteration_range_start_is_defined()) {
			if (check_if_loop_variable_is_defined()) {
				Expect(4 /* "$" */);
				Expect(_ident);
				Expect(24 /* "=" */);
			}
			Number(number);
			Expect(25 /* "to" */);
		}
		Number(number);
		if (la->kind == 26 /* "step" */) {
			Get();
			if (la->kind == 7 /* "-" */) {
				Get();
			}
			Number(number);
		}
		Expect(27 /* "do" */);
		StatementList(loop_body);
		Expect(28 /* "rof" */);
}

void Parser::IfStatement(std::optional<statement::ptr> &statement ) {
		expression_evaluation_result condition;
		expression_evaluation_result closing_condition;
		statement::vec true_branch{};
		statement::vec false_branch{};
		
		Expect(29 /* "if" */);
		Expression(condition);
		Expect(30 /* "then" */);
		StatementList(true_branch);
		Expect(31 /* "else" */);
		StatementList(false_branch);
		Expect(32 /* "fi" */);
		Expression(closing_condition);
}

void Parser::UnaryStatement(std::optional<statement::ptr> &statement ) {
		signal_evaluation_result unary_stmt_operand;	
		if (la->kind == 33 /* "~" */) {
			Get();
		} else if (la->kind == 34 /* "++" */) {
			Get();
		} else if (la->kind == 35 /* "--" */) {
			Get();
		} else SynErr(62);
		Expect(24 /* "=" */);
		Signal(unary_stmt_operand);
}

void Parser::SkipStatement(std::optional<statement::ptr> &statement ) {
		Expect(38 /* "skip" */);
}

void Parser::AssignStatement(std::optional<statement::ptr> &statement ) {
		signal_evaluation_result assign_stmt_lhs;
		expression_evaluation_result assign_stmt_rhs;
		
		Signal(assign_stmt_lhs);
		if (la->kind == 36 /* "^" */) {
			Get();
		} else if (la->kind == 6 /* "+" */) {
			Get();
		} else if (la->kind == 7 /* "-" */) {
			Get();
		} else SynErr(63);
		Expect(24 /* "=" */);
		Expression(assign_stmt_rhs);
}

void Parser::SwapStatement(std::optional<statement::ptr> &statement ) {
		signal_evaluation_result swap_me, swap_there;	
		Signal(swap_me);
		Expect(37 /* "<=>" */);
		Signal(swap_there);
}

void Parser::Expression(expression_evaluation_result &expression) {
		signal_evaluation_result signal;
		std::optional<number::ptr> number;
		
		if (StartOf(1)) {
			if (check_if_expression_is_number()) {
				Number(number);
			} else if (check_if_expression_is_binary_expression()) {
				BinaryExpression(expression);
			} else {
				ShiftExpression(expression);
			}
		} else if (la->kind == _ident) {
			Signal(signal);
		} else if (la->kind == 33 /* "~" */ || la->kind == 52 /* "!" */) {
			UnaryExpression(expression);
		} else SynErr(64);
}

void Parser::Signal(signal_evaluation_result &signal_access) {
		variable_access::ptr signal;	
		Expect(_ident);
		const std::string signal_ident = convert_to_uniform_text_format(t->val);
		if (!current_symbol_table_scope->contains(signal_ident)) {
		// TODO: GEN_ERROR
		}
		else {
		signal.reset(new variable_access());
		// TODO: Set with variable from symbol table
		signal->set_var({});
		}
		
		while (la->kind == 18 /* "[" */) {
			Get();
			expression_evaluation_result index_expression;	
			Expression(index_expression);
			Expect(19 /* "]" */);
		}
		if (la->kind == 39 /* "." */) {
			std::optional<number::ptr> range_start, range_end;
			bool defined_range = false;
			
			Get();
			Number(range_start);
			if (la->kind == 40 /* ":" */) {
				Get();
				Number(range_end);
				defined_range = true;	
			}
			if (!range_start.has_value() || (defined_range && !range_end.has_value())) {
			return;
			}
			
			bool isBitIndex = range_end.has_value();
			if (isBitIndex) {
			// TODO:
			}
			else {
			// TODO:
			}
			
		}
}

void Parser::BinaryExpression(expression_evaluation_result &binary_expression) {
		expression_evaluation_result binary_expr_lhs;
		expression_evaluation_result binary_expr_rhs;
		
		Expect(5 /* "(" */);
		Expression(binary_expr_lhs);
		switch (la->kind) {
		case 6 /* "+" */: {
			Get();
			break;
		}
		case 7 /* "-" */: {
			Get();
			break;
		}
		case 36 /* "^" */: {
			Get();
			break;
		}
		case 8 /* "*" */: {
			Get();
			break;
		}
		case 9 /* "/" */: {
			Get();
			break;
		}
		case 41 /* "%" */: {
			Get();
			break;
		}
		case 42 /* "*>" */: {
			Get();
			break;
		}
		case 43 /* "&&" */: {
			Get();
			break;
		}
		case 44 /* "||" */: {
			Get();
			break;
		}
		case 45 /* "&" */: {
			Get();
			break;
		}
		case 46 /* "|" */: {
			Get();
			break;
		}
		case 47 /* "<" */: {
			Get();
			break;
		}
		case 48 /* ">" */: {
			Get();
			break;
		}
		case 24 /* "=" */: {
			Get();
			break;
		}
		case 49 /* "!=" */: {
			Get();
			break;
		}
		case 50 /* "<=" */: {
			Get();
			break;
		}
		case 51 /* ">=" */: {
			Get();
			break;
		}
		default: SynErr(65); break;
		}
		Expression(binary_expr_rhs);
		Expect(10 /* ")" */);
}

void Parser::ShiftExpression(expression_evaluation_result &shift_expression) {
		expression_evaluation_result shift_expression_lhs;
		std::optional<number::ptr> shift_amount;
		
		Expect(5 /* "(" */);
		Expression(shift_expression_lhs);
		if (la->kind == 53 /* "<<" */) {
			Get();
		} else if (la->kind == 54 /* ">>" */) {
			Get();
		} else SynErr(66);
		Number(shift_amount);
		Expect(10 /* ")" */);
}

void Parser::UnaryExpression(expression_evaluation_result &unary_expression) {
		expression_evaluation_result unary_expression_operand;	
		if (la->kind == 52 /* "!" */) {
			Get();
		} else if (la->kind == 33 /* "~" */) {
			Get();
		} else SynErr(67);
		Expression(unary_expression_operand);
}




// If the user declared a method Init and a mehtod Destroy they should
// be called in the contructur and the destructor respctively.
//
// The following templates are used to recognize if the user declared
// the methods Init and Destroy.

template<typename T>
struct ParserInitExistsRecognizer {
	template<typename U, void (U::*)() = &U::Init>
	struct ExistsIfInitIsDefinedMarker{};

	struct InitIsMissingType {
		char dummy1;
	};
	
	struct InitExistsType {
		char dummy1; char dummy2;
	};

	// exists always
	template<typename U>
	static InitIsMissingType is_here(...);

	// exist only if ExistsIfInitIsDefinedMarker is defined
	template<typename U>
	static InitExistsType is_here(ExistsIfInitIsDefinedMarker<U>*);

	enum { InitExists = (sizeof(is_here<T>(NULL)) == sizeof(InitExistsType)) };
};

template<typename T>
struct ParserDestroyExistsRecognizer {
	template<typename U, void (U::*)() = &U::Destroy>
	struct ExistsIfDestroyIsDefinedMarker{};

	struct DestroyIsMissingType {
		char dummy1;
	};
	
	struct DestroyExistsType {
		char dummy1; char dummy2;
	};

	// exists always
	template<typename U>
	static DestroyIsMissingType is_here(...);

	// exist only if ExistsIfDestroyIsDefinedMarker is defined
	template<typename U>
	static DestroyExistsType is_here(ExistsIfDestroyIsDefinedMarker<U>*);

	enum { DestroyExists = (sizeof(is_here<T>(NULL)) == sizeof(DestroyExistsType)) };
};

// The folloing templates are used to call the Init and Destroy methods if they exist.

// Generic case of the ParserInitCaller, gets used if the Init method is missing
template<typename T, bool = ParserInitExistsRecognizer<T>::InitExists>
struct ParserInitCaller {
	static void CallInit(T *t) {
		// nothing to do
	}
};

// True case of the ParserInitCaller, gets used if the Init method exists
template<typename T>
struct ParserInitCaller<T, true> {
	static void CallInit(T *t) {
		t->Init();
	}
};

// Generic case of the ParserDestroyCaller, gets used if the Destroy method is missing
template<typename T, bool = ParserDestroyExistsRecognizer<T>::DestroyExists>
struct ParserDestroyCaller {
	static void CallDestroy(T *t) {
		// nothing to do
	}
};

// True case of the ParserDestroyCaller, gets used if the Destroy method exists
template<typename T>
struct ParserDestroyCaller<T, true> {
	static void CallDestroy(T *t) {
		t->Destroy();
	}
};

void Parser::Parse() {
	t = NULL;
	la = dummyToken = new Token();
	la->val = coco_string_create(L"Dummy Token");
	Get();
	SyReC();
	Expect(0);
}

Parser::Parser(Scanner *scanner) {
	maxT = 55;

	ParserInitCaller<Parser>::CallInit(this);
	dummyToken = NULL;
	t = la = NULL;
	minErrDist = 2;
	errDist = minErrDist;
	this->scanner = scanner;
	errors = new Errors();
}

bool Parser::StartOf(int s) {
	const bool T = true;
	const bool x = false;

	static bool set[2][57] = {
		{T,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x},
		{x,x,T,T, T,T,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x,x,x,x, x}
	};



	return set[s][la->kind];
}

Parser::~Parser() {
	ParserDestroyCaller<Parser>::CallDestroy(this);
	delete errors;
	delete dummyToken;
}

Errors::Errors() {
	count = 0;
}

void Errors::SynErr(int line, int col, int n) {
	wchar_t* s;
	switch (n) {
			case 0: s = coco_string_create(L"EOF expected"); break;
			case 1: s = coco_string_create(L"ident expected"); break;
			case 2: s = coco_string_create(L"int expected"); break;
			case 3: s = coco_string_create(L"\"#\" expected"); break;
			case 4: s = coco_string_create(L"\"$\" expected"); break;
			case 5: s = coco_string_create(L"\"(\" expected"); break;
			case 6: s = coco_string_create(L"\"+\" expected"); break;
			case 7: s = coco_string_create(L"\"-\" expected"); break;
			case 8: s = coco_string_create(L"\"*\" expected"); break;
			case 9: s = coco_string_create(L"\"/\" expected"); break;
			case 10: s = coco_string_create(L"\")\" expected"); break;
			case 11: s = coco_string_create(L"\"module\" expected"); break;
			case 12: s = coco_string_create(L"\",\" expected"); break;
			case 13: s = coco_string_create(L"\"in\" expected"); break;
			case 14: s = coco_string_create(L"\"out\" expected"); break;
			case 15: s = coco_string_create(L"\"inout\" expected"); break;
			case 16: s = coco_string_create(L"\"wire\" expected"); break;
			case 17: s = coco_string_create(L"\"signal\" expected"); break;
			case 18: s = coco_string_create(L"\"[\" expected"); break;
			case 19: s = coco_string_create(L"\"]\" expected"); break;
			case 20: s = coco_string_create(L"\";\" expected"); break;
			case 21: s = coco_string_create(L"\"call\" expected"); break;
			case 22: s = coco_string_create(L"\"uncall\" expected"); break;
			case 23: s = coco_string_create(L"\"for\" expected"); break;
			case 24: s = coco_string_create(L"\"=\" expected"); break;
			case 25: s = coco_string_create(L"\"to\" expected"); break;
			case 26: s = coco_string_create(L"\"step\" expected"); break;
			case 27: s = coco_string_create(L"\"do\" expected"); break;
			case 28: s = coco_string_create(L"\"rof\" expected"); break;
			case 29: s = coco_string_create(L"\"if\" expected"); break;
			case 30: s = coco_string_create(L"\"then\" expected"); break;
			case 31: s = coco_string_create(L"\"else\" expected"); break;
			case 32: s = coco_string_create(L"\"fi\" expected"); break;
			case 33: s = coco_string_create(L"\"~\" expected"); break;
			case 34: s = coco_string_create(L"\"++\" expected"); break;
			case 35: s = coco_string_create(L"\"--\" expected"); break;
			case 36: s = coco_string_create(L"\"^\" expected"); break;
			case 37: s = coco_string_create(L"\"<=>\" expected"); break;
			case 38: s = coco_string_create(L"\"skip\" expected"); break;
			case 39: s = coco_string_create(L"\".\" expected"); break;
			case 40: s = coco_string_create(L"\":\" expected"); break;
			case 41: s = coco_string_create(L"\"%\" expected"); break;
			case 42: s = coco_string_create(L"\"*>\" expected"); break;
			case 43: s = coco_string_create(L"\"&&\" expected"); break;
			case 44: s = coco_string_create(L"\"||\" expected"); break;
			case 45: s = coco_string_create(L"\"&\" expected"); break;
			case 46: s = coco_string_create(L"\"|\" expected"); break;
			case 47: s = coco_string_create(L"\"<\" expected"); break;
			case 48: s = coco_string_create(L"\">\" expected"); break;
			case 49: s = coco_string_create(L"\"!=\" expected"); break;
			case 50: s = coco_string_create(L"\"<=\" expected"); break;
			case 51: s = coco_string_create(L"\">=\" expected"); break;
			case 52: s = coco_string_create(L"\"!\" expected"); break;
			case 53: s = coco_string_create(L"\"<<\" expected"); break;
			case 54: s = coco_string_create(L"\">>\" expected"); break;
			case 55: s = coco_string_create(L"??? expected"); break;
			case 56: s = coco_string_create(L"invalid Number"); break;
			case 57: s = coco_string_create(L"invalid Number"); break;
			case 58: s = coco_string_create(L"invalid SignalList"); break;
			case 59: s = coco_string_create(L"invalid Parameter"); break;
			case 60: s = coco_string_create(L"invalid Statement"); break;
			case 61: s = coco_string_create(L"invalid CallStatement"); break;
			case 62: s = coco_string_create(L"invalid UnaryStatement"); break;
			case 63: s = coco_string_create(L"invalid AssignStatement"); break;
			case 64: s = coco_string_create(L"invalid Expression"); break;
			case 65: s = coco_string_create(L"invalid BinaryExpression"); break;
			case 66: s = coco_string_create(L"invalid ShiftExpression"); break;
			case 67: s = coco_string_create(L"invalid UnaryExpression"); break;

		default:
		{
			wchar_t format[20];
			coco_swprintf(format, 20, L"error %d", n);
			s = coco_string_create(format);
		}
		break;
	}
	wprintf(L"-- line %d col %d: %ls\n", line, col, s);
	coco_string_delete(s);
	count++;
}

void Errors::Error(int line, int col, const wchar_t *s) {
	wprintf(L"-- line %d col %d: %ls\n", line, col, s);
	count++;
}

void Errors::Warning(int line, int col, const wchar_t *s) {
	wprintf(L"-- line %d col %d: %ls\n", line, col, s);
}

void Errors::Warning(const wchar_t *s) {
	wprintf(L"%ls\n", s);
}

void Errors::Exception(const wchar_t* s) {
	wprintf(L"%ls", s); 
	exit(1);
}

} // namespace

